export const API_URL = "http://localhost:8000/api";
export const LOCAL_STORAGE_TOKEN_NAME = "findrest";
export const RESTAURANTS_LOADED_SUCCESS = "RESTAURANTS_LOADED_SUCCESS";
export const RESTAURANTS_LOADED_FAIL = "RESTAURANTS_LOADED_FAIL";
export const FIND_RESTAURANT = "FIND_RESTAURANT";
export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const DELETE_RESTAURANT = "DELETE_RESTAURANT";
export const UPDATE_RESTAURANT = "UPDATE_RESTAURANT";
